spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor_db?useSSL=false
    username: root


# JPA setting
  jpa.hibernate.ddl-auto: update

# Configurer Spring MVC pour utiliser la stratégie de correspondance de chemins
# ANT_PATH_MATCHER , permettant de gérer des modèles de chemins flexibles
# comme /** ou /*.html
#
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER